[package]
name = "plotters_normal_graph"
version = "0.1.0"
edition = "2021"

[dependencies]
plotters = {version="0.3.7", features=["ttf"]}
plotters-bitmap = "0.3.7"
nalgebra = "0.33.2"
minifb = "0.23.0"
